INSERT INTO public.country (id, iso_code, name) VALUES (1, 'AFG', 'Afghanistan');
INSERT INTO public.country (id, iso_code, name) VALUES (2, 'ALB', 'Albania');
INSERT INTO public.country (id, iso_code, name) VALUES (3, 'DZA', 'Algeria');
INSERT INTO public.country (id, iso_code, name) VALUES (4, 'AND', 'Andorra');
INSERT INTO public.country (id, iso_code, name) VALUES (5, 'AGO', 'Angola');
INSERT INTO public.country (id, iso_code, name) VALUES (6, 'AIA', 'Anguilla');
INSERT INTO public.country (id, iso_code, name) VALUES (7, 'ATG', 'Antigua and Barbuda');
INSERT INTO public.country (id, iso_code, name) VALUES (8, 'ARG', 'Argentina');
INSERT INTO public.country (id, iso_code, name) VALUES (9, 'ARM', 'Armenia');
INSERT INTO public.country (id, iso_code, name) VALUES (10, 'ABW', 'Aruba');
INSERT INTO public.country (id, iso_code, name) VALUES (11, 'AUS', 'Australia');
INSERT INTO public.country (id, iso_code, name) VALUES (12, 'AUT', 'Austria');
INSERT INTO public.country (id, iso_code, name) VALUES (13, 'AZE', 'Azerbaijan');
INSERT INTO public.country (id, iso_code, name) VALUES (14, 'BHS', 'Bahamas');
INSERT INTO public.country (id, iso_code, name) VALUES (15, 'BHR', 'Bahrain');
INSERT INTO public.country (id, iso_code, name) VALUES (16, 'BGD', 'Bangladesh');
INSERT INTO public.country (id, iso_code, name) VALUES (17, 'BRB', 'Barbados');
INSERT INTO public.country (id, iso_code, name) VALUES (18, 'BLR', 'Belarus');
INSERT INTO public.country (id, iso_code, name) VALUES (19, 'BEL', 'Belgium');
INSERT INTO public.country (id, iso_code, name) VALUES (20, 'BLZ', 'Belize');
INSERT INTO public.country (id, iso_code, name) VALUES (21, 'BEN', 'Benin');
INSERT INTO public.country (id, iso_code, name) VALUES (22, 'BMU', 'Bermuda');
INSERT INTO public.country (id, iso_code, name) VALUES (23, 'BTN', 'Bhutan');
INSERT INTO public.country (id, iso_code, name) VALUES (24, 'BOL', 'Bolivia');
INSERT INTO public.country (id, iso_code, name) VALUES (25, 'BES', 'Bonaire Sint Eustatius and Saba');
INSERT INTO public.country (id, iso_code, name) VALUES (26, 'BIH', 'Bosnia and Herzegovina');
INSERT INTO public.country (id, iso_code, name) VALUES (27, 'BWA', 'Botswana');
INSERT INTO public.country (id, iso_code, name) VALUES (28, 'BRA', 'Brazil');
INSERT INTO public.country (id, iso_code, name) VALUES (29, 'VGB', 'British Virgin Islands');
INSERT INTO public.country (id, iso_code, name) VALUES (30, 'BRN', 'Brunei');
INSERT INTO public.country (id, iso_code, name) VALUES (31, 'BGR', 'Bulgaria');
INSERT INTO public.country (id, iso_code, name) VALUES (32, 'BFA', 'Burkina Faso');
INSERT INTO public.country (id, iso_code, name) VALUES (33, 'BDI', 'Burundi');
INSERT INTO public.country (id, iso_code, name) VALUES (34, 'KHM', 'Cambodia');
INSERT INTO public.country (id, iso_code, name) VALUES (35, 'CMR', 'Cameroon');
INSERT INTO public.country (id, iso_code, name) VALUES (36, 'CAN', 'Canada');
INSERT INTO public.country (id, iso_code, name) VALUES (37, 'CPV', 'Cape Verde');
INSERT INTO public.country (id, iso_code, name) VALUES (38, 'CYM', 'Cayman Islands');
INSERT INTO public.country (id, iso_code, name) VALUES (39, 'CAF', 'Central African Republic');
INSERT INTO public.country (id, iso_code, name) VALUES (40, 'TCD', 'Chad');
INSERT INTO public.country (id, iso_code, name) VALUES (41, 'CHL', 'Chile');
INSERT INTO public.country (id, iso_code, name) VALUES (42, 'CHN', 'China');
INSERT INTO public.country (id, iso_code, name) VALUES (43, 'COL', 'Colombia');
INSERT INTO public.country (id, iso_code, name) VALUES (44, 'COM', 'Comoros');
INSERT INTO public.country (id, iso_code, name) VALUES (45, 'COG', 'Congo');
INSERT INTO public.country (id, iso_code, name) VALUES (46, 'COK', 'Cook Islands');
INSERT INTO public.country (id, iso_code, name) VALUES (47, 'CRI', 'Costa Rica');
INSERT INTO public.country (id, iso_code, name) VALUES (48, 'CIV', 'Cote d''Ivoire');
INSERT INTO public.country (id, iso_code, name) VALUES (49, 'HRV', 'Croatia');
INSERT INTO public.country (id, iso_code, name) VALUES (50, 'CUB', 'Cuba');
INSERT INTO public.country (id, iso_code, name) VALUES (51, 'CUW', 'Curacao');
INSERT INTO public.country (id, iso_code, name) VALUES (52, 'CYP', 'Cyprus');
INSERT INTO public.country (id, iso_code, name) VALUES (53, 'CZE', 'Czechia');
INSERT INTO public.country (id, iso_code, name) VALUES (54, 'COD', 'Democratic Republic of Congo');
INSERT INTO public.country (id, iso_code, name) VALUES (55, 'DNK', 'Denmark');
INSERT INTO public.country (id, iso_code, name) VALUES (56, 'DJI', 'Djibouti');
INSERT INTO public.country (id, iso_code, name) VALUES (57, 'DMA', 'Dominica');
INSERT INTO public.country (id, iso_code, name) VALUES (58, 'DOM', 'Dominican Republic');
INSERT INTO public.country (id, iso_code, name) VALUES (59, 'ECU', 'Ecuador');
INSERT INTO public.country (id, iso_code, name) VALUES (60, 'EGY', 'Egypt');
INSERT INTO public.country (id, iso_code, name) VALUES (61, 'SLV', 'El Salvador');
INSERT INTO public.country (id, iso_code, name) VALUES (62, 'ENG', 'England');
INSERT INTO public.country (id, iso_code, name) VALUES (63, 'GNQ', 'Equatorial Guinea');
INSERT INTO public.country (id, iso_code, name) VALUES (64, 'EST', 'Estonia');
INSERT INTO public.country (id, iso_code, name) VALUES (65, 'SWZ', 'Eswatini');
INSERT INTO public.country (id, iso_code, name) VALUES (66, 'ETH', 'Ethiopia');
INSERT INTO public.country (id, iso_code, name) VALUES (67, 'FRO', 'Faeroe Islands');
INSERT INTO public.country (id, iso_code, name) VALUES (68, 'FLK', 'Falkland Islands');
INSERT INTO public.country (id, iso_code, name) VALUES (69, 'FJI', 'Fiji');
INSERT INTO public.country (id, iso_code, name) VALUES (70, 'FIN', 'Finland');
INSERT INTO public.country (id, iso_code, name) VALUES (71, 'FRA', 'France');
INSERT INTO public.country (id, iso_code, name) VALUES (72, 'PYF', 'French Polynesia');
INSERT INTO public.country (id, iso_code, name) VALUES (73, 'GAB', 'Gabon');
INSERT INTO public.country (id, iso_code, name) VALUES (74, 'GMB', 'Gambia');
INSERT INTO public.country (id, iso_code, name) VALUES (75, 'GEO', 'Georgia');
INSERT INTO public.country (id, iso_code, name) VALUES (76, 'DEU', 'Germany');
INSERT INTO public.country (id, iso_code, name) VALUES (77, 'GHA', 'Ghana');
INSERT INTO public.country (id, iso_code, name) VALUES (78, 'GIB', 'Gibraltar');
INSERT INTO public.country (id, iso_code, name) VALUES (79, 'GRC', 'Greece');
INSERT INTO public.country (id, iso_code, name) VALUES (80, 'GRL', 'Greenland');
INSERT INTO public.country (id, iso_code, name) VALUES (81, 'GRD', 'Grenada');
INSERT INTO public.country (id, iso_code, name) VALUES (82, 'GTM', 'Guatemala');
INSERT INTO public.country (id, iso_code, name) VALUES (83, 'GGY', 'Guernsey');
INSERT INTO public.country (id, iso_code, name) VALUES (84, 'GIN', 'Guinea');
INSERT INTO public.country (id, iso_code, name) VALUES (85, 'GNB', 'Guinea-Bissau');
INSERT INTO public.country (id, iso_code, name) VALUES (86, 'GUY', 'Guyana');
INSERT INTO public.country (id, iso_code, name) VALUES (87, 'HTI', 'Haiti');
INSERT INTO public.country (id, iso_code, name) VALUES (88, 'HND', 'Honduras');
INSERT INTO public.country (id, iso_code, name) VALUES (89, 'HKG', 'Hong Kong');
INSERT INTO public.country (id, iso_code, name) VALUES (90, 'HUN', 'Hungary');
INSERT INTO public.country (id, iso_code, name) VALUES (91, 'ISL', 'Iceland');
INSERT INTO public.country (id, iso_code, name) VALUES (92, 'IND', 'India');
INSERT INTO public.country (id, iso_code, name) VALUES (93, 'IDN', 'Indonesia');
INSERT INTO public.country (id, iso_code, name) VALUES (94, 'IRN', 'Iran');
INSERT INTO public.country (id, iso_code, name) VALUES (95, 'IRQ', 'Iraq');
INSERT INTO public.country (id, iso_code, name) VALUES (96, 'IRL', 'Ireland');
INSERT INTO public.country (id, iso_code, name) VALUES (97, 'IMN', 'Isle of Man');
INSERT INTO public.country (id, iso_code, name) VALUES (98, 'ISR', 'Israel');
INSERT INTO public.country (id, iso_code, name) VALUES (99, 'ITA', 'Italy');
INSERT INTO public.country (id, iso_code, name) VALUES (100, 'JAM', 'Jamaica');
INSERT INTO public.country (id, iso_code, name) VALUES (101, 'JPN', 'Japan');
INSERT INTO public.country (id, iso_code, name) VALUES (102, 'JEY', 'Jersey');
INSERT INTO public.country (id, iso_code, name) VALUES (103, 'JOR', 'Jordan');
INSERT INTO public.country (id, iso_code, name) VALUES (104, 'KAZ', 'Kazakhstan');
INSERT INTO public.country (id, iso_code, name) VALUES (105, 'KEN', 'Kenya');
INSERT INTO public.country (id, iso_code, name) VALUES (106, 'KIR', 'Kiribati');
INSERT INTO public.country (id, iso_code, name) VALUES (107, 'KOS', 'Kosovo');
INSERT INTO public.country (id, iso_code, name) VALUES (108, 'KWT', 'Kuwait');
INSERT INTO public.country (id, iso_code, name) VALUES (109, 'KGZ', 'Kyrgyzstan');
INSERT INTO public.country (id, iso_code, name) VALUES (110, 'LAO', 'Laos');
INSERT INTO public.country (id, iso_code, name) VALUES (111, 'LVA', 'Latvia');
INSERT INTO public.country (id, iso_code, name) VALUES (112, 'LBN', 'Lebanon');
INSERT INTO public.country (id, iso_code, name) VALUES (113, 'LSO', 'Lesotho');
INSERT INTO public.country (id, iso_code, name) VALUES (114, 'LBR', 'Liberia');
INSERT INTO public.country (id, iso_code, name) VALUES (115, 'LBY', 'Libya');
INSERT INTO public.country (id, iso_code, name) VALUES (116, 'LIE', 'Liechtenstein');
INSERT INTO public.country (id, iso_code, name) VALUES (117, 'LTU', 'Lithuania');
INSERT INTO public.country (id, iso_code, name) VALUES (118, 'LUX', 'Luxembourg');
INSERT INTO public.country (id, iso_code, name) VALUES (119, 'MAC', 'Macao');
INSERT INTO public.country (id, iso_code, name) VALUES (120, 'MDG', 'Madagascar');
INSERT INTO public.country (id, iso_code, name) VALUES (121, 'MWI', 'Malawi');
INSERT INTO public.country (id, iso_code, name) VALUES (122, 'MYS', 'Malaysia');
INSERT INTO public.country (id, iso_code, name) VALUES (123, 'MDV', 'Maldives');
INSERT INTO public.country (id, iso_code, name) VALUES (124, 'MLI', 'Mali');
INSERT INTO public.country (id, iso_code, name) VALUES (125, 'MLT', 'Malta');
INSERT INTO public.country (id, iso_code, name) VALUES (126, 'MRT', 'Mauritania');
INSERT INTO public.country (id, iso_code, name) VALUES (127, 'MUS', 'Mauritius');
INSERT INTO public.country (id, iso_code, name) VALUES (128, 'MEX', 'Mexico');
INSERT INTO public.country (id, iso_code, name) VALUES (129, 'MDA', 'Moldova');
INSERT INTO public.country (id, iso_code, name) VALUES (130, 'MCO', 'Monaco');
INSERT INTO public.country (id, iso_code, name) VALUES (131, 'MNG', 'Mongolia');
INSERT INTO public.country (id, iso_code, name) VALUES (132, 'MNE', 'Montenegro');
INSERT INTO public.country (id, iso_code, name) VALUES (133, 'MSR', 'Montserrat');
INSERT INTO public.country (id, iso_code, name) VALUES (134, 'MAR', 'Morocco');
INSERT INTO public.country (id, iso_code, name) VALUES (135, 'MOZ', 'Mozambique');
INSERT INTO public.country (id, iso_code, name) VALUES (136, 'MMR', 'Myanmar');
INSERT INTO public.country (id, iso_code, name) VALUES (137, 'NAM', 'Namibia');
INSERT INTO public.country (id, iso_code, name) VALUES (138, 'NRU', 'Nauru');
INSERT INTO public.country (id, iso_code, name) VALUES (139, 'NPL', 'Nepal');
INSERT INTO public.country (id, iso_code, name) VALUES (140, 'NLD', 'Netherlands');
INSERT INTO public.country (id, iso_code, name) VALUES (141, 'NCL', 'New Caledonia');
INSERT INTO public.country (id, iso_code, name) VALUES (142, 'NZL', 'New Zealand');
INSERT INTO public.country (id, iso_code, name) VALUES (143, 'NIC', 'Nicaragua');
INSERT INTO public.country (id, iso_code, name) VALUES (144, 'NER', 'Niger');
INSERT INTO public.country (id, iso_code, name) VALUES (145, 'NGA', 'Nigeria');
INSERT INTO public.country (id, iso_code, name) VALUES (146, 'NIU', 'Niue');
INSERT INTO public.country (id, iso_code, name) VALUES (147, 'MKD', 'North Macedonia');
INSERT INTO public.country (id, iso_code, name) VALUES (148, 'CYN', 'Northern Cyprus');
INSERT INTO public.country (id, iso_code, name) VALUES (149, 'NIR', 'Northern Ireland');
INSERT INTO public.country (id, iso_code, name) VALUES (150, 'NOR', 'Norway');
INSERT INTO public.country (id, iso_code, name) VALUES (151, 'OMN', 'Oman');
INSERT INTO public.country (id, iso_code, name) VALUES (152, 'PAK', 'Pakistan');
INSERT INTO public.country (id, iso_code, name) VALUES (153, 'PSE', 'Palestine');
INSERT INTO public.country (id, iso_code, name) VALUES (154, 'PAN', 'Panama');
INSERT INTO public.country (id, iso_code, name) VALUES (155, 'PNG', 'Papua New Guinea');
INSERT INTO public.country (id, iso_code, name) VALUES (156, 'PRY', 'Paraguay');
INSERT INTO public.country (id, iso_code, name) VALUES (157, 'PER', 'Peru');
INSERT INTO public.country (id, iso_code, name) VALUES (158, 'PHL', 'Philippines');
INSERT INTO public.country (id, iso_code, name) VALUES (159, 'PCN', 'Pitcairn');
INSERT INTO public.country (id, iso_code, name) VALUES (160, 'POL', 'Poland');
INSERT INTO public.country (id, iso_code, name) VALUES (161, 'PRT', 'Portugal');
INSERT INTO public.country (id, iso_code, name) VALUES (162, 'QAT', 'Qatar');
INSERT INTO public.country (id, iso_code, name) VALUES (163, 'ROU', 'Romania');
INSERT INTO public.country (id, iso_code, name) VALUES (164, 'RUS', 'Russia');
INSERT INTO public.country (id, iso_code, name) VALUES (165, 'RWA', 'Rwanda');
INSERT INTO public.country (id, iso_code, name) VALUES (166, 'SHN', 'Saint Helena');
INSERT INTO public.country (id, iso_code, name) VALUES (167, 'KNA', 'Saint Kitts and Nevis');
INSERT INTO public.country (id, iso_code, name) VALUES (168, 'LCA', 'Saint Lucia');
INSERT INTO public.country (id, iso_code, name) VALUES (169, 'VCT', 'Saint Vincent and the Grenadines');
INSERT INTO public.country (id, iso_code, name) VALUES (170, 'WSM', 'Samoa');
INSERT INTO public.country (id, iso_code, name) VALUES (171, 'SMR', 'San Marino');
INSERT INTO public.country (id, iso_code, name) VALUES (172, 'STP', 'Sao Tome and Principe');
INSERT INTO public.country (id, iso_code, name) VALUES (173, 'SAU', 'Saudi Arabia');
INSERT INTO public.country (id, iso_code, name) VALUES (174, 'SCT', 'Scotland');
INSERT INTO public.country (id, iso_code, name) VALUES (175, 'SEN', 'Senegal');
INSERT INTO public.country (id, iso_code, name) VALUES (176, 'SRB', 'Serbia');
INSERT INTO public.country (id, iso_code, name) VALUES (177, 'SYC', 'Seychelles');
INSERT INTO public.country (id, iso_code, name) VALUES (178, 'SLE', 'Sierra Leone');
INSERT INTO public.country (id, iso_code, name) VALUES (179, 'SGP', 'Singapore');
INSERT INTO public.country (id, iso_code, name) VALUES (180, 'SXM', 'Sint Maarten (Dutch part)');
INSERT INTO public.country (id, iso_code, name) VALUES (181, 'SVK', 'Slovakia');
INSERT INTO public.country (id, iso_code, name) VALUES (182, 'SVN', 'Slovenia');
INSERT INTO public.country (id, iso_code, name) VALUES (183, 'SLB', 'Solomon Islands');
INSERT INTO public.country (id, iso_code, name) VALUES (184, 'SOM', 'Somalia');
INSERT INTO public.country (id, iso_code, name) VALUES (185, 'ZAF', 'South Africa');
INSERT INTO public.country (id, iso_code, name) VALUES (186, 'KOR', 'South Korea');
INSERT INTO public.country (id, iso_code, name) VALUES (187, 'SSD', 'South Sudan');
INSERT INTO public.country (id, iso_code, name) VALUES (188, 'ESP', 'Spain');
INSERT INTO public.country (id, iso_code, name) VALUES (189, 'LKA', 'Sri Lanka');
INSERT INTO public.country (id, iso_code, name) VALUES (190, 'SDN', 'Sudan');
INSERT INTO public.country (id, iso_code, name) VALUES (191, 'SUR', 'Suriname');
INSERT INTO public.country (id, iso_code, name) VALUES (192, 'SWE', 'Sweden');
INSERT INTO public.country (id, iso_code, name) VALUES (193, 'CHE', 'Switzerland');
INSERT INTO public.country (id, iso_code, name) VALUES (194, 'SYR', 'Syria');
INSERT INTO public.country (id, iso_code, name) VALUES (195, 'TWN', 'Taiwan');
INSERT INTO public.country (id, iso_code, name) VALUES (196, 'TJK', 'Tajikistan');
INSERT INTO public.country (id, iso_code, name) VALUES (197, 'TZA', 'Tanzania');
INSERT INTO public.country (id, iso_code, name) VALUES (198, 'THA', 'Thailand');
INSERT INTO public.country (id, iso_code, name) VALUES (199, 'TLS', 'Timor');
INSERT INTO public.country (id, iso_code, name) VALUES (200, 'TGO', 'Togo');
INSERT INTO public.country (id, iso_code, name) VALUES (201, 'TKL', 'Tokelau');
INSERT INTO public.country (id, iso_code, name) VALUES (202, 'TON', 'Tonga');
INSERT INTO public.country (id, iso_code, name) VALUES (203, 'TTO', 'Trinidad and Tobago');
INSERT INTO public.country (id, iso_code, name) VALUES (204, 'TUN', 'Tunisia');
INSERT INTO public.country (id, iso_code, name) VALUES (205, 'TUR', 'Turkey');
INSERT INTO public.country (id, iso_code, name) VALUES (206, 'TKM', 'Turkmenistan');
INSERT INTO public.country (id, iso_code, name) VALUES (207, 'TCA', 'Turks and Caicos Islands');
INSERT INTO public.country (id, iso_code, name) VALUES (208, 'TUV', 'Tuvalu');
INSERT INTO public.country (id, iso_code, name) VALUES (209, 'UGA', 'Uganda');
INSERT INTO public.country (id, iso_code, name) VALUES (210, 'UKR', 'Ukraine');
INSERT INTO public.country (id, iso_code, name) VALUES (211, 'ARE', 'United Arab Emirates');
INSERT INTO public.country (id, iso_code, name) VALUES (212, 'GBR', 'United Kingdom');
INSERT INTO public.country (id, iso_code, name) VALUES (213, 'USA', 'United States');
INSERT INTO public.country (id, iso_code, name) VALUES (214, 'URY', 'Uruguay');
INSERT INTO public.country (id, iso_code, name) VALUES (215, 'UZB', 'Uzbekistan');
INSERT INTO public.country (id, iso_code, name) VALUES (216, 'VUT', 'Vanuatu');
INSERT INTO public.country (id, iso_code, name) VALUES (217, 'VEN', 'Venezuela');
INSERT INTO public.country (id, iso_code, name) VALUES (218, 'VNM', 'Vietnam');
INSERT INTO public.country (id, iso_code, name) VALUES (219, 'WLS', 'Wales');
INSERT INTO public.country (id, iso_code, name) VALUES (220, 'WLF', 'Wallis and Futuna');
INSERT INTO public.country (id, iso_code, name) VALUES (221, 'YEM', 'Yemen');
INSERT INTO public.country (id, iso_code, name) VALUES (222, 'ZMB', 'Zambia');
INSERT INTO public.country (id, iso_code, name) VALUES (223, 'ZWE', 'Zimbabwe');
INSERT INTO public.country (id, iso_code, name) VALUES (224, '-', 'European Union');
