INSERT INTO public.source (id, website, name) VALUES (1, 'https://covid19.who.int/', 'World Health Organization');
INSERT INTO public.source (id, website, name) VALUES (2, 'https://shendetesia.gov.al/vaksinimi-anticovid-2754244-vaksinime/', 'Ministry of Health');
INSERT INTO public.source (id, website, name) VALUES (3, 'https://www.government.aw', 'Government of Aruba');
INSERT INTO public.source (id, website, name) VALUES (4, 'https://covidbaseau.com/', 'Government of Australia via CovidBaseAU');
INSERT INTO public.source (id, website, name) VALUES (5, 'https://koronavirusinfo.az', 'Government of Azerbaijan');
INSERT INTO public.source (id, website, name) VALUES (6, 'https://ais.paho.org/imm/IM_DosisAdmin-Vacunacion.asp', 'Pan American Health Organization');
INSERT INTO public.source (id, website, name) VALUES (7, 'http://103.247.238.92/webportal/pages/covid19-vaccination-update.php', 'Directorate General of Health Services');
INSERT INTO public.source (id, website, name) VALUES (8, 'https://epistat.wiv-isp.be/covid/', 'Sciensano');
INSERT INTO public.source (id, website, name) VALUES (9, 'https://github.com/dquintani/vacunacion/', 'Ministry of Health via https://www.boligrafica.com/');
INSERT INTO public.source (id, website, name) VALUES (10, 'https://covid19.who.int/', 'Africa Centres for Disease Control and Prevention');
INSERT INTO public.source (id, website, name) VALUES (11, 'https://coronavirusbra1.github.io', 'State governments via coronavirusbra1.github.io');
INSERT INTO public.source (id, website, name) VALUES (12, 'https://covid19tracker.ca/vaccinationtracker.html', 'Official data from provinces via covid19tracker.ca');
INSERT INTO public.source (id, website, name) VALUES (13, 'https://github.com/MinCiencia/Datos-COVID19', 'Ministry of Health, via Ministry of Science GitHub repository');
INSERT INTO public.source (id, website, name) VALUES (14, 'http://www.nhc.gov.cn/jkj/s7915/202203/d81d339daf694f97952f10d9d8604143.shtml', 'National Health Commission');
INSERT INTO public.source (id, website, name) VALUES (15, 'https://stats.pacificdata.org/vis?tm=covid&pg=0&df[ds]=SPC2&df[id]=DF_COVID_VACCINATION&df[ag]=SPC&df[vs]=1.0', 'SPC Public Health Division');
INSERT INTO public.source (id, website, name) VALUES (16, 'https://www.ccss.sa.cr/web/coronavirus/vacunacion', 'Costa Rican Social Security Fund');
INSERT INTO public.source (id, website, name) VALUES (17, 'https://bakuna.cw/', 'Government of Curacao');
INSERT INTO public.source (id, website, name) VALUES (18, 'https://covid19.ssi.dk/overvagningsdata/download-fil-med-vaccinationsdata', 'Statens Serum Institute');
INSERT INTO public.source (id, website, name) VALUES (19, 'https://vacunate.gob.do/', 'Ministry of Public Health');
INSERT INTO public.source (id, website, name) VALUES (20, 'https://github.com/andrab/ecuacovid', 'Government of Ecuador via Ecuacovid');
INSERT INTO public.source (id, website, name) VALUES (21, 'https://coronavirus.data.gov.uk/details/vaccinations', 'Government of the United Kingdom');
INSERT INTO public.source (id, website, name) VALUES (22, 'https://opendata.digilugu.ee', 'National Health Board');
INSERT INTO public.source (id, website, name) VALUES (23, 'https://corona.fo/api', 'Government of the Faeroe Islands');
INSERT INTO public.source (id, website, name) VALUES (24, 'https://www.facebook.com/FalkIandsGov/posts/4401230323224594', 'Government of the Falkland Islands');
INSERT INTO public.source (id, website, name) VALUES (25, 'https://sampo.thl.fi/pivot/prod/en/vaccreg/cov19cov/fact_cov19cov', 'Finnish Institute for Health and Welfare');
INSERT INTO public.source (id, website, name) VALUES (26, 'https://www.data.gouv.fr/fr/datasets/donnees-relatives-aux-personnes-vaccinees-contre-la-covid-19-1/', 'Public Health France');
INSERT INTO public.source (id, website, name) VALUES (27, 'https://vaccines.ncdc.ge/vaccinationprocess/', 'National Center for Disease Control and Public Health');
INSERT INTO public.source (id, website, name) VALUES (28, 'https://impfdashboard.de/', 'Robert Koch Institut');
INSERT INTO public.source (id, website, name) VALUES (29, 'https://twitter.com/GibraltarGov/status/1507008369005015050', 'Government of Gibraltar');
INSERT INTO public.source (id, website, name) VALUES (30, 'https://corona.nun.gl', 'Government of Greenland');
INSERT INTO public.source (id, website, name) VALUES (31, 'https://covid19.gov.gg/guidance/vaccine/stats', 'Government of Guernsey');
INSERT INTO public.source (id, website, name) VALUES (32, 'https://covid19.who.int/', 'National Health Security Agency');
INSERT INTO public.source (id, website, name) VALUES (33, 'https://data.gov.hk/en-data/dataset/hk-fhb-fhbcovid19-vaccination-rates-over-time-by-age', 'Food and Health Bureau');
INSERT INTO public.source (id, website, name) VALUES (34, 'https://koronavirus.gov.hu//cikkek/6-millio-402-ezer-beoltott-2906-az-uj-fertozott-es-elhunyt-40-beteg', 'Government of Hungary');
INSERT INTO public.source (id, website, name) VALUES (35, 'https://www.covid.is/tolulegar-upplysingar-boluefni', 'Directorate of Health');
INSERT INTO public.source (id, website, name) VALUES (36, 'https://dashboard.cowin.gov.in/', 'Government of India');
INSERT INTO public.source (id, website, name) VALUES (37, 'https://data.covid19.go.id/public/index.html', 'Government of Indonesia');
INSERT INTO public.source (id, website, name) VALUES (38, 'https://covid19ireland-geohive.hub.arcgis.com/', 'Heath Service Executive');
INSERT INTO public.source (id, website, name) VALUES (39, 'https://covid19.gov.im/general-information/covid-19-vaccination-statistics/', 'Isle of Man Government');
INSERT INTO public.source (id, website, name) VALUES (40, 'https://datadashboard.health.gov.il/COVID-19/general', 'Government of Israel');
INSERT INTO public.source (id, website, name) VALUES (41, 'https://raw.githubusercontent.com/italia/covid19-opendata-vaccini/master/dati/somministrazioni-vaccini-latest.csv', 'Extraordinary commissioner for the Covid-19 emergency');
INSERT INTO public.source (id, website, name) VALUES (42, 'https://www.kantei.go.jp/jp/headline/kansensho/vaccine.html', 'Prime Minister''s Office');
INSERT INTO public.source (id, website, name) VALUES (43, 'https://www.gov.je/Datasets/ListOpenData?ListName=COVID19Weekly&clean=true', 'Government of Jersey');
INSERT INTO public.source (id, website, name) VALUES (44, 'https://www.coronavirus2020.kz/', 'Government of Kazakhstan');
INSERT INTO public.source (id, website, name) VALUES (45, 'https://data.gov.lv/dati/eng/dataset/covid19-vakcinacijas', 'National Health Service');
INSERT INTO public.source (id, website, name) VALUES (46, 'https://impact.cib.gov.lb/home/dashboard/vaccine', 'Government of Lebanon');
INSERT INTO public.source (id, website, name) VALUES (47, 'https://opendata.swiss/en/dataset/covid-19-schweiz?detGeo=FL', 'Federal Office of Public Health');
INSERT INTO public.source (id, website, name) VALUES (48, 'https://data.public.lu/en/datasets/donnees-covid19/#_', 'Government of Luxembourg');
INSERT INTO public.source (id, website, name) VALUES (49, 'https://www.ssm.gov.mo/docs/19164/19164_dd2dfe6b739b4964b394d629e656af72_000_.pdf', 'Government of Macao');
INSERT INTO public.source (id, website, name) VALUES (50, 'https://github.com/MoH-Malaysia/covid19-public', 'Government of Malaysia');
INSERT INTO public.source (id, website, name) VALUES (51, 'https://twitter.com/HPA_MV/status/1503053275741913088', 'Presidency of the Maldives');
INSERT INTO public.source (id, website, name) VALUES (52, 'https://github.com/COVID19-Malta/COVID19-Cases', 'COVID-19 Malta Public Health Response Team');
INSERT INTO public.source (id, website, name) VALUES (53, 'http://www.gob.mx/cms/uploads/attachment/file/712810/2022.03.29_17h00_ComunicadoTecnicoDiario_Covid19__1_.pdf', 'Secretary of Health');
INSERT INTO public.source (id, website, name) VALUES (54, 'https://en.gouv.mc/Policy-Practice/Social-Affairs-and-Health/News/Minister-of-State-visits-those-working-to-combat-COVID', 'National Council');
INSERT INTO public.source (id, website, name) VALUES (55, 'https://ikon.mn/', 'Ministry of Health via ikon.mn');
INSERT INTO public.source (id, website, name) VALUES (56, 'https://www.covidodgovor.me/', 'Government of Montenegro');
INSERT INTO public.source (id, website, name) VALUES (57, 'https://github.com/mzelst/covid-19', 'European CDC, via Marino van Zelst');
INSERT INTO public.source (id, website, name) VALUES (58, 'https://worldhealthorg.shinyapps.io/EURO_COVID-19_vaccine_monitor/', 'Government of North Macedonia');
INSERT INTO public.source (id, website, name) VALUES (59, 'https://github.com/folkehelseinstituttet/surveillance_data', 'Norwegian Institute of Public Health');
INSERT INTO public.source (id, website, name) VALUES (60, 'https://ncoc.gov.pk/covid-vaccination-en.php', 'National Command and Operation Centre');
INSERT INTO public.source (id, website, name) VALUES (61, 'https://www.datosabiertos.gob.pe/dataset/vacunacion', 'Ministerio de Salud via github.com/jmcastagnetto/covid-19-peru-vacunas');
INSERT INTO public.source (id, website, name) VALUES (62, 'https://news.abs-cbn.com/spotlight/multimedia/infographic/03/23/21/philippines-covid-19-vaccine-tracker', 'Department of Health via ABS-CBN Investigative and Research Group');
INSERT INTO public.source (id, website, name) VALUES (63, 'https://github.com/dssg-pt/covid19pt-data', 'Directorate General for Health via Data Science for Social Good');
INSERT INTO public.source (id, website, name) VALUES (64, 'https://datelazi.ro/', 'Government of Romania via datelazi.ro');
INSERT INTO public.source (id, website, name) VALUES (65, 'https://gogov.ru/articles/covid-v-stats', 'Official data from local governments via gogov.ru');
INSERT INTO public.source (id, website, name) VALUES (66, 'https://www.sainthelena.gov.sh/2021/news/preliminary-data-from-the-covid-19-vaccination-programme/', 'Government of Saint Helena');
INSERT INTO public.source (id, website, name) VALUES (67, 'https://covid19.who.int/', 'Saudi Health Council');
INSERT INTO public.source (id, website, name) VALUES (68, 'https://vakcinacija.gov.rs/', 'Government of Serbia');
INSERT INTO public.source (id, website, name) VALUES (69, 'https://data.gov.sg/dataset/covid-19-vaccination', 'Government of Singapore');
INSERT INTO public.source (id, website, name) VALUES (70, 'https://covid-19.sledilnik.org/sl/stats', 'National Institute of Public Health via covid-19.sledilnik.org');
INSERT INTO public.source (id, website, name) VALUES (71, 'https://ncv.kdca.go.kr/', 'Korea Centers for Disease Control and Prevention');
INSERT INTO public.source (id, website, name) VALUES (72, 'https://www.epid.gov.lk/web/images/pdf/corona_vaccination/covid_vaccination_2022-03_22.pdf', 'Ministry of Health''s Epidemiology Unit');
INSERT INTO public.source (id, website, name) VALUES (73, 'https://laatjevaccineren.sr/', 'Government of Suriname');
INSERT INTO public.source (id, website, name) VALUES (74, 'https://fohm.se/smittskydd-beredskap/utbrott/aktuella-utbrott/covid-19/statistik-och-analyser/statistik-over-registrerade-vaccinationer-covid-19/', 'Public Health Agency of Sweden');
INSERT INTO public.source (id, website, name) VALUES (75, 'https://www.cdc.gov.tw/Category/Page/9jFXNbCe-sFK9EImRRi2Og', 'Taiwan Centers for Disease Control');
INSERT INTO public.source (id, website, name) VALUES (76, 'https://ddc.moph.go.th/covid19-dashboard/', 'Government of Thailand');
INSERT INTO public.source (id, website, name) VALUES (77, 'https://covid19asi.saglik.gov.tr/', 'COVID-19 Vaccine Information Platform');
INSERT INTO public.source (id, website, name) VALUES (78, 'https://fcsc.gov.ae/en-us/Pages/Covid19/UAE-Covid-19-Updates.aspx', 'National Emergency Crisis and Disaster Management Authority');
INSERT INTO public.source (id, website, name) VALUES (79, 'https://data.cdc.gov/Vaccinations/COVID-19-Vaccination-Trends-in-the-United-States-N/rh2h-3yt2', 'Centers for Disease Control and Prevention');
INSERT INTO public.source (id, website, name) VALUES (80, 'https://monitor.uruguaysevacuna.gub.uy/', 'Ministry of Health via vacuna.uy');
INSERT INTO public.source (id, website, name) VALUES (81, 'https://rtc-planning.maps.arcgis.com/apps/dashboards/3b3a01c1d8444932ba075fb44b119b63', 'Government of Zambia');
