INSERT INTO public.vaccine (id, name) VALUES (1, 'Johnson&Johnson');
INSERT INTO public.vaccine (id, name) VALUES (2, 'Oxford/AstraZeneca');
INSERT INTO public.vaccine (id, name) VALUES (3, 'Pfizer/BioNTech');
INSERT INTO public.vaccine (id, name) VALUES (4, 'Sinopharm/Beijing');
INSERT INTO public.vaccine (id, name) VALUES (5, 'Sinovac');
INSERT INTO public.vaccine (id, name) VALUES (6, 'Sputnik V');
INSERT INTO public.vaccine (id, name) VALUES (7, 'Moderna');
INSERT INTO public.vaccine (id, name) VALUES (8, 'CanSino');
INSERT INTO public.vaccine (id, name) VALUES (9, 'Novavax');
INSERT INTO public.vaccine (id, name) VALUES (10, 'Sputnik Light');
INSERT INTO public.vaccine (id, name) VALUES (11, 'Covaxin');
INSERT INTO public.vaccine (id, name) VALUES (12, 'Sinopharm/Wuhan');
INSERT INTO public.vaccine (id, name) VALUES (13, 'ZF2001');
INSERT INTO public.vaccine (id, name) VALUES (14, 'Abdala');
INSERT INTO public.vaccine (id, name) VALUES (15, 'Soberana Plus');
INSERT INTO public.vaccine (id, name) VALUES (16, 'Soberana02');
INSERT INTO public.vaccine (id, name) VALUES (17, 'COVIran Barekat');
INSERT INTO public.vaccine (id, name) VALUES (18, 'FAKHRAVAC');
INSERT INTO public.vaccine (id, name) VALUES (19, 'Razi Cov Pars');
INSERT INTO public.vaccine (id, name) VALUES (20, 'SpikoGen');
INSERT INTO public.vaccine (id, name) VALUES (21, 'QazVac');
INSERT INTO public.vaccine (id, name) VALUES (22, 'EpiVacCorona');
INSERT INTO public.vaccine (id, name) VALUES (23, 'Medigen');
INSERT INTO public.vaccine (id, name) VALUES (24, 'Turkovac');
